spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://127.0.0.1:3308/inventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: inventory_service
    password: password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
