spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://127.0.0.1:3308/inventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: inventory_service
    password: password
    hikari:
      maximum-pool-size: 5
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect